### ISSUE TITLE
I do not see the availables sites in the media folder form

### ISSUE THREAD

**Issue by mraiffe** [open-orchestra/open-orchestra-media-admin-bundle#167]
1. When I edit a media folder I do not see my current site
2. I create a new site
3. When I edit a media folder I do not see the 2 sites, the list is empty 

Without those informations, I don't know if the folder is visible for my current site or for all sites

**Comment by alavieille** [comment]
it's fixed in this PR: https://github.com/open-orchestra/open-orchestra-media-admin-bundle/pull/160
