### ISSUE TITLE
Cannot display media upload files form in short window browser

### ISSUE THREAD

**Issue by mraiffe** [open-orchestra/open-orchestra-media-admin-bundle#175]
If you open the media upload form in a browser in full size window the form appear correctly. But if you decrease the size of the window the form did not change it display but simply disappear.
![capture du 2016-03-18 14 02 11](https://cloud.githubusercontent.com/assets/5470027/13878520/455d045e-ed12-11e5-8e42-4504ad1bf180.png)

**Comment by alavieille** [comment]
it is fixes in this PR https://github.com/open-orchestra/open-orchestra-media-admin-bundle/pull/180
