### ISSUE TITLE
Should a content block cache invalidation be triggerred when updating a linked media ?

### ISSUE THREAD

**Issue by ghost** [open-orchestra/open-orchestra-media-admin-bundle#183]
In most of the cases I have in my application, when a content is displayed, linked medias are displayed too. So, in order to refresh html code of medias (like title or alt), on blocks related to content, I had to add a cache tag for each linked media.
So I just wondering if a media update should trigger an invalidation of cache for contents that reference the media. I think it would be useful in most of cases.

**Comment by ngilain** [comment]
We will see this for the 1.2 tag

**Comment by alavieille** [comment]
This is added in these PR https://github.com/open-orchestra/open-orchestra-model-bundle/pull/632
https://github.com/open-orchestra/open-orchestra-model-interface/pull/216
https://github.com/open-orchestra/open-orchestra-media-admin-bundle/pull/277
thanks
