### ISSUE TITLE
Migration script to update existing media references

### ISSUE THREAD

**Issue by ghost** [open-orchestra/open-orchestra-media-admin-bundle#192]
From version 1.1.0-alpha4 to 1.1.0-beta, storage of media references has been updated. It was a string starting with "media-" and is now an array containing "id" and "format".
Opening the update form of a content that has an attribute value to an old format leads to an error, so it is not possible to just update the media using BO interface. It can be useful to have a migration script to do this update from old to new format.

**Comment by ngilain** [comment]
The migration script for the hole media application has been merged into the master and will be available in stable version with the tag 1.1

You can have a look at the PR here : https://github.com/open-orchestra/open-orchestra-media-admin-bundle/commit/3263463420518a69819ec704df22748ffb9ce300
