### ISSUE TITLE
removeUsageReference on null

### ISSUE THREAD

**Issue by Thiblef** [open-orchestra/open-orchestra-media-admin-bundle#221]
A media added in a node can be supressed from the mediateque if the node isn't published.
Once the media is suppressed the node continue to contain the media references.
And an error is throw when I want to change the node status:

```
Error: Call to a member function removeUsageReference() on null
vendor/open-orchestra/open-orchestra-media-admin-bundle/MediaAdminBundle/EventSubscriber/UpdateMediaReferenceSubscriber.php at line 102
```

I think it could be good to check if the media isn't null before deal with the media usage references.

**Comment by alavieille** [comment]
This is fixed in https://github.com/open-orchestra/open-orchestra-media-admin-bundle/pull/226 for branch  master and https://github.com/open-orchestra/open-orchestra-media-admin-bundle/pull/227 for branch 1.1
