### ISSUE TITLE
Display problem when no media selected on 'oo_media' field on content form

### ISSUE THREAD

**Issue by ghost** [open-orchestra/open-orchestra-media-admin-bundle#233]
When no media is selected on a 'oo_media' field on a content form, the text "No media selected" and the "Browse" button are overlapping.

Version of Open Orchestra : 1.1.0
Browser : Firefox 46.0 on Ubuntu

![capture du 2016-05-17 09 41 25](https://cloud.githubusercontent.com/assets/15613074/15314768/2a1a590e-1c14-11e6-8850-4fab62ef1b03.png)

**Comment by djamnazi** [comment]
bug fixed
