### ISSUE TITLE
FolderEvent cannot be override

### ISSUE THREAD

**Issue by ghost** [open-orchestra/open-orchestra-media-admin-bundle#234]
Events of type `FolderEvent` are instantiated directly in `MediaAdminBundle/Controller/Admin/FolderController` and `MediaAdminBundle/Controller/Api/FolderController` with a `new FolderEvent($folder)`. This block all possibility of redefining the FolderEvent without overriding controllers.

**Comment by alavieille** [comment]
We will see this for the 1.2 tag

**Comment by djamnazi** [comment]
Issues resolved
