### ISSUE TITLE
No thumbnail/alternative generated on image with high width/height ratio

### ISSUE THREAD

**Issue by ghost** [open-orchestra/open-orchestra-media-admin-bundle#243]
When uploading an image having a high width/height ratio, thumbnail and alternative fails to generate.

OO version : 1.1

Test image 
![separateur-evo_980](https://cloud.githubusercontent.com/assets/15613074/15783790/fa8df35e-29af-11e6-8c24-478c19ab1a36.jpg)

**Comment by veolys-nanne** [comment]
on road map

**Comment by ngilain** [comment]
This is fixed on https://github.com/open-orchestra/open-orchestra-media-admin-bundle/pull/246

Thank you for the feedback
