### ISSUE TITLE
Fill media meta with EXIF informations

### ISSUE THREAD

**Issue by ghost** [open-orchestra/open-orchestra-media-admin-bundle#249]
## Informations

**Orchestra Version** : 1.1

**Issue Type**: 
- [ ] Bug
- [x] Feature request
- [ ] Question
## Description

Some images can embed metadata in EXIF tags. It could be usefull to automatically fill some of media attributes with these informations.

See http://owl.phy.queensu.ca/~phil/exiftool/TagNames/EXIF.html

**Comment by ngilain** [comment]
Thank you for your feedback, we will work on this on a future realease.

**Comment by alavieille** [comment]
This is added in PR https://github.com/open-orchestra/open-orchestra-media-admin-bundle/pull/273
https://github.com/open-orchestra/open-orchestra-media-bundle/pull/228
thanks
