### ISSUE TITLE
MediaTransformer should use TranslationChoiceManagerInterface

### ISSUE THREAD

**Issue by clement-michelet** [open-orchestra/open-orchestra-media-admin-bundle#262]
## Informations

**Orchestra Version** : 
1.0, 1.1, master

**Issue Type**: 
- [ ] Bug
- [x] Feature request
- [ ] Question
## Description

The class MediaTransformer use `TranslationChoiceManager` when there is an interface `TranslationChoiceManagerInterface`. It should use the interface.

**Comment by alavieille** [comment]
This is fixed in 1.1 and master https://github.com/open-orchestra/open-orchestra-media-admin-bundle/pull/269, https://github.com/open-orchestra/open-orchestra-media-admin-bundle/pull/268.
thanks
