### ISSUE TITLE
Image insertion problem in TinyMCE context

### ISSUE THREAD

**Issue by ghost** [open-orchestra/open-orchestra-media-admin-bundle#279]
## Informations

**Orchestra Version** : 1.1

**Issue Type**: 
- [x] Bug
- [ ] Feature request
- [ ] Question
## Description

Sometimes, when inserting an image in a rich text, inserted image is not the selected one. It happens when user had started an image insertion procedure without finishing it on the same session.
### Steps to reproduce the problem

1) Open the creation form of a content having a rich text field.
2) Open the image insertion modal.
3) Click on the image IMG1.
4) Close the modal (without validating).
5) Open the image insertion modal a second time.
6) Click on the image IMG2.
7) Validate your choice.
-> Inserted image is IMG1 instead of IMG2.

**Comment by alavieille** [comment]
This is fixed in this PR https://github.com/open-orchestra/open-orchestra-media-admin-bundle/pull/289 and  https://github.com/open-orchestra/open-orchestra-media-admin-bundle/pull/286
