### ISSUE TITLE
Gestion de permissions sur les dossiers de la médiathèque

### ISSUE THREAD

**Issue by clement-michelet** [open-orchestra/open-orchestra-media-admin-bundle#41]
Il serait bien de pouvoir avoir la possibilité de définir un droit d'accès en lecture / écriture sur un dossier de la médiathèque en fonction d'un groupe utilisateur.

**Comment by nicolasThal** [comment]
This might be done in version 1.1

**Comment by alavieille** [comment]
it's fixed in this PR https://github.com/open-orchestra/open-orchestra-media-admin-bundle/pull/62
