### ISSUE TITLE
Procedure d'installation

### ISSUE THREAD

**Issue by senprog** [open-orchestra/open-orchestra-media-admin-bundle#411]
Bonjour,
je suis très interessé par ce bundle, mais étant novice dans symfony, il serai tres agréable de mettre une procedure d'installation et une sandbox d'utilisation du bundle. 

Merci et cordialement.

**Comment by alavieille** [comment]
Bonjour,

Ce bundle est une dépendance au Back Office Open Orchestra, il ne peut fonctionner que sur un Back Office Open Orchestra. Donc je ne sais pas si cela correspond a votre besoin.

Concernant l'installation elle est disponible dans la documentation du CMS (http://open-orchestra.readthedocs.io/fr/1.2/summary_dev_guide.html#installation).

La documentation concerne la version 1.2, celle de la version 2.0 est en cours de rédaction
