### ISSUE TITLE
L'ajout de classe au bouton d'import de media bloque l'import

### ISSUE THREAD

**Issue by clement-michelet** [open-orchestra/open-orchestra-media-admin-bundle#46]
Fautif: https://github.com/open-orchestra/open-orchestra-media-admin-bundle/blob/master/MediaAdminBundle/Resources/public/coffee/GalleryCollectionView.coffee#L47

Pour reproduire le problème, il suffit d'ajouter une classe CSS au bouton en utilisant Firebug ou l'outil de développement de Chrome.

Le problème est que le sélecteur jQuery utilisé ne supporte pas de multiples classes. Avec de multiple classes, le sélecteur est : `$('#main .class1 class2 class3')` si l'élément a pour classes `class1 class2 class3`.

**Comment by alavieille** [comment]
it's fixed in this PR https://github.com/open-orchestra/open-orchestra-media-admin-bundle/pull/57/files
