### ISSUE TITLE
Permettre de filtrer les médias d'un dossier par mimeType

### ISSUE THREAD

**Issue by clement-michelet** [open-orchestra/open-orchestra-media-admin-bundle#48]
Nous utilisons la modale de sélection de média.  Dans certains cas, nous devons sélectionner :
- uniquement des images
- uniquement des vidéos

Hors, pour l'instant, les images et les vidéos ne peuvent être sélectionnées sans restriction. Il serait bien de pouvoir lister via l'API les médias dans un dossier en appliquant un filtre (ex: mimeType).

**Comment by nicolasThal** [comment]
This is in the roadmap, but we have other priority to solve first.
